/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.yovany.eventos.ui;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static org.springframework.data.jpa.domain.AbstractPersistable_.id;

/**
 *
 * @author DELL
 */
public class editar extends javax.swing.JFrame {

    /**
     * Creates new form editar
     */
    public editar() {
        initComponents();
         ocultarCampos(); 
    }
     // Método para ocultar los campos de datos hasta que se busque el evento
    private void ocultarCampos() {
        nombreTextField.setVisible(false);
        lugarTextField.setVisible(false);
        fechaTextField.setVisible(false);
        horaTextField.setVisible(false);
}
      // Método para mostrar los campos de datos después de la búsqueda exitosa
    private void mostrarCampos() {
        nombreTextField.setVisible(true);
        lugarTextField.setVisible(true);
        fechaTextField.setVisible(true);
        horaTextField.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        regresar = new javax.swing.JToggleButton();
        buscarButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lugarTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        fechaTextField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        horaTextField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        guardarButton = new javax.swing.JToggleButton();
        cancelarButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel1.setText("ID del Evento");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 40));

        idTextField.setBackground(new java.awt.Color(242, 242, 242));
        idTextField.setBorder(null);
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        bg.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 20));

        regresar.setText("MENU PRINCIPAL");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        bg.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 150, 40));

        buscarButton.setText("BUSCAR EVENTO");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        bg.add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 150, 40));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel2.setText("Nombre del Evento");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 30));

        nombreTextField.setBackground(new java.awt.Color(242, 242, 242));
        nombreTextField.setBorder(null);
        bg.add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 220, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setText("Lugar del Evento");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 220, 30));

        lugarTextField.setBackground(new java.awt.Color(242, 242, 242));
        lugarTextField.setBorder(null);
        lugarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarTextFieldActionPerformed(evt);
            }
        });
        bg.add(lugarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 220, 10));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel4.setText("Fecha del Evento");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 30));

        fechaTextField.setBackground(new java.awt.Color(242, 242, 242));
        fechaTextField.setBorder(null);
        bg.add(fechaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 180, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 220, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5.setText("Hora del Evento");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 140, 40));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        horaTextField.setBorder(null);
        bg.add(horaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 180, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 220, 20));

        guardarButton.setText("GUARDAR CAMBIOS");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        bg.add(guardarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 150, 40));

        cancelarButton.setText("CANCELAR");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        bg.add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        String idEvento = idTextField.getText();
    String nombre = nombreTextField.getText();
    String lugar = lugarTextField.getText();
    String fecha = fechaTextField.getText();
    String hora = horaTextField.getText();

    try {
        URL url = new URL("http://localhost:8080/eventos/" + idEvento);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("PUT");
        conn.setRequestProperty("Content-Type", "application/json");
        conn.setDoOutput(true);

        // Crear el cuerpo JSON con los datos actualizados
        String jsonInputString = String.format(
                "{\"nombre\": \"%s\", \"lugar\": \"%s\", \"fecha\": \"%s\", \"hora\": \"%s\"}",
                nombre, lugar, fecha, hora
        );

        try (OutputStream os = conn.getOutputStream()) {
            byte[] input = jsonInputString.getBytes("utf-8");
            os.write(input, 0, input.length);
        }

        if (conn.getResponseCode() == HttpURLConnection.HTTP_OK) {
            JOptionPane.showMessageDialog(this, "Cambios guardados exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el evento.");
        }

        conn.disconnect();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar los cambios: " + e.getMessage());
    }
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
     Menu newframe= new Menu();
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
                                                   
    String idEvento = idTextField.getText();

    try {
        // URL de la API para buscar el evento por ID
        URL url = new URL("http://localhost:8080/eventos/" + idEvento);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("GET");
        conn.setRequestProperty("Accept", "application/json");

        if (conn.getResponseCode() == HttpURLConnection.HTTP_OK) {
            // Leemos la respuesta de la API
            BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            StringBuilder response = new StringBuilder();
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            // Convertimos la respuesta JSON a los campos
            String jsonResponse = response.toString();

            // Aquí puedes utilizar una biblioteca como Jackson o Gson para mapear el JSON a un objeto
            // Ejemplo:
            // Evento evento = new ObjectMapper().readValue(jsonResponse, Evento.class);
            // nombreTextField.setText(evento.getNombre());
            // lugarTextField.setText(evento.getLugar());
            // fechaTextField.setText(evento.getFecha());
            // horaTextField.setText(evento.getHora());

            mostrarCampos();  // Mostramos los campos después de encontrar el evento
            JOptionPane.showMessageDialog(this, "Evento encontrado exitosamente.");

        } else {
            JOptionPane.showMessageDialog(this, "Evento no encontrado.");
        }

        conn.disconnect();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al buscar el evento: " + e.getMessage());
    }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
         // Limpiamos todos los campos y ocultamos los datos
        idTextField.setText("");
        nombreTextField.setText("");
        lugarTextField.setText("");
        fechaTextField.setText("");
        horaTextField.setText("");
        ocultarCampos();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void lugarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JToggleButton buscarButton;
    private javax.swing.JToggleButton cancelarButton;
    private javax.swing.JTextField fechaTextField;
    private javax.swing.JToggleButton guardarButton;
    private javax.swing.JTextField horaTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField lugarTextField;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JToggleButton regresar;
    // End of variables declaration//GEN-END:variables
}
