/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.yovany.eventos.ui;
import com.yovany.eventos.ui.RegistroEventos;
/**
 *
 * @author Yovany
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        bg = new javax.swing.JPanel();
        tituloeventos = new javax.swing.JLabel();
        agregar1 = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JToggleButton();
        invitados = new javax.swing.JToggleButton();
        cerrarsesion = new javax.swing.JToggleButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloeventos.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        tituloeventos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloeventos.setText("EVENTOS");
        bg.add(tituloeventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 120, 50));

        agregar1.setBackground(new java.awt.Color(0, 204, 204));
        agregar1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        agregar1.setText("AGREGAR");
        agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar1ActionPerformed(evt);
            }
        });
        bg.add(agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 120, 40));

        editar.setBackground(new java.awt.Color(0, 204, 204));
        editar.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        bg.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 120, 40));

        eliminar.setBackground(new java.awt.Color(0, 204, 204));
        eliminar.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        bg.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 120, 50));

        invitados.setBackground(new java.awt.Color(0, 204, 204));
        invitados.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        invitados.setText("Invitados");
        invitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invitadosActionPerformed(evt);
            }
        });
        bg.add(invitados, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 120, 50));

        cerrarsesion.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        cerrarsesion.setText("CERRAR SESION");
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });
        bg.add(cerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        editar newframe= new editar();
        newframe.setVisible(true);
        
        this.dispose();
                
    }//GEN-LAST:event_editarActionPerformed

    private void agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar1ActionPerformed
       RegistroEventos newframe= new RegistroEventos();
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_agregar1ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Eliminar newframe= new Eliminar();
        newframe.setVisible(true);
        
        this.dispose();
      
    }//GEN-LAST:event_eliminarActionPerformed

    private void invitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invitadosActionPerformed
       invitados newframe= new invitados();
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_invitadosActionPerformed

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
       Login newframe= new Login();
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_cerrarsesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar1;
    private javax.swing.JPanel bg;
    private javax.swing.JToggleButton cerrarsesion;
    private javax.swing.JButton editar;
    private javax.swing.JToggleButton eliminar;
    private javax.swing.JToggleButton invitados;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel tituloeventos;
    // End of variables declaration//GEN-END:variables
}
